/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oscar.nbamatchs;

import java.awt.Image;
import java.net.URL;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;

import com.oscar.model.MongoController;

/**
 *
 * @author oscar
 */
public class PlayerCard extends javax.swing.JFrame {

	/**
	 * Creates new form PlayerCard
	 */
	private MongoController controller;
	private String url_logo = "https://library.kissclipart.com/20190218/uaq/kissclipart-anonymous-person-clipart-anonymous-anonymity-338725fd49c63393.png";

	public PlayerCard() {
		this.controller = new MongoController();
		initComponents();
		try {
			this.player_photo.setIcon(new ImageIcon(
					new ImageIcon(ImageIO.read(new URL(this.url_logo)), "Team 1 Logo").getImage().getScaledInstance(
							this.player_photo.getWidth(), this.player_photo.getHeight(), Image.SCALE_DEFAULT)));
			this.player_photo.setIcon(new ImageIcon(
					new ImageIcon(ImageIO.read(new URL(this.url_logo)), "Team 2 Logo").getImage().getScaledInstance(
							this.player_photo.getWidth(), this.player_photo.getHeight(), Image.SCALE_DEFAULT)));
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	public void insertItems(JComboBox<String> jcombo, MongoController controller) {
		List<String> lista = controller.getTeams();
		for (int i = 0; i < lista.size(); i++) {
			jcombo.addItem(lista.get(i));
		}
	}

	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		player_photo = new javax.swing.JLabel();
		name_field = new javax.swing.JTextField();
		weight_field = new javax.swing.JTextField();
		heigh_field = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox<>();
		draft_year = new javax.swing.JTextField();
		draft_number = new javax.swing.JTextField();
		thumbnail_text = new javax.swing.JTextField();
		submit_button = new javax.swing.JButton();
		jComboBox2 = new javax.swing.JComboBox<>();
		university_field = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		jComboBox2.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "BA", "ES", "AL", "AP","P" }));

		submit_button.setText("Submit");
		this.name_field.setToolTipText("Name");
		this.weight_field.setToolTipText("Weight");
		this.heigh_field.setToolTipText("Heigh");
		this.jComboBox1.setToolTipText("Teams");
		this.jComboBox2.setToolTipText("Positions");
		this.draft_number.setToolTipText("Draft number");
		this.draft_year.setToolTipText("Draft year");
		this.university_field.setToolTipText("University");
		this.thumbnail_text.setToolTipText("Thumbnail");
		this.insertItems(jComboBox1, this.controller);
		submit_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				submitButtonActionPerformed(evt);
			}
		});
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
										.createSequentialGroup().addComponent(player_photo,
												javax.swing.GroupLayout.PREFERRED_SIZE, 122,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126,
												Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																name_field, javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 140,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(layout.createSequentialGroup()
																.addComponent(heigh_field,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 68,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(weight_field)))
														.addGap(0, 0, Short.MAX_VALUE))
												.addGroup(layout.createSequentialGroup()
														.addComponent(jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE, 68,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(
																jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 68,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup()
														.addComponent(draft_year,
																javax.swing.GroupLayout.PREFERRED_SIZE, 68,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(10, 10, 10).addComponent(draft_number))))
								.addGroup(layout.createSequentialGroup().addComponent(submit_button)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(thumbnail_text, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(
												university_field, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(player_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 123,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
						.addComponent(submit_button))
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(weight_field, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(heigh_field, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(draft_year, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(draft_number, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(university_field, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(thumbnail_text, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PlayerCard.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PlayerCard.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PlayerCard.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PlayerCard.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PlayerCard().setVisible(true);
			}
		});
	}

	private void submitButtonActionPerformed(java.awt.event.ActionEvent ext) {
		this.controller.createPlayer(this.name_field.getText(), Double.parseDouble(this.weight_field.getText()),
				Double.parseDouble(this.heigh_field.getText()), (String) this.jComboBox1.getSelectedItem(),
				(String) this.jComboBox2.getSelectedItem(), this.draft_year.getText(),
				Integer.parseInt(this.draft_number.getText()), this.university_field.getText(),
				this.thumbnail_text.getText());
		try {
			this.player_photo.setIcon(
					new ImageIcon(new ImageIcon(ImageIO.read(new URL(this.thumbnail_text.getText())), "Team 1 Logo")
							.getImage().getScaledInstance(this.player_photo.getWidth(), this.player_photo.getHeight(),
									Image.SCALE_DEFAULT)));
			this.draft_number.setText(Integer.toString(Integer.parseInt(this.draft_number.getText())+1));
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField weight_field;
	private javax.swing.JTextField draft_number;
	private javax.swing.JTextField draft_year;
	private javax.swing.JTextField heigh_field;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox2;
	private javax.swing.JTextField name_field;
	private javax.swing.JLabel player_photo;
	private javax.swing.JButton submit_button;
	private javax.swing.JTextField thumbnail_text;
	private javax.swing.JTextField university_field;
	// End of variables declaration//GEN-END:variables
}
